### ISSUE TITLE
When I run demo.py to visualize:python demo.py --config-file configs/sparse_inst_r50_giam.yaml --input datasets/coco/val2017/000000000139.jpg --output results --opt MODEL.WEIGHTS models/sparse_inst_r50_giam_aug_2b7d68.pth INPUT.MIN_SIZE_TEST 512

### ISSUE THREAD

**Issue by zhouzhou-github1** [hustvl/SparseInst#13]
[04/15 12:48:11 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/sparse_inst_r50_giam.yaml', input=['datasets/coco/val2017/000000000139.jpg'], opts=['MODEL.WEIGHTS', 'models/sparse_inst_r50_giam_aug_2b7d68.pth', 'INPUT.MIN_SIZE_TEST', '512'], output='results', video_input=None, webcam=False)
[04/15 12:48:13 fvcore.common.checkpoint]: [Checkpointer] Loading from models/sparse_inst_r50_giam_aug_2b7d68.pth ...
  0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]/home/zhou/anaconda3/envs/sc_depth_env/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811805959/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 96, in <module>
    img, args.confidence_threshold)
  File "/home/zhou/program/SparseInst-main/sparseinst/d2_predictor.py", line 68, in run_on_image
    vis_output = visualizer.draw_instance_predictions(predictions=instances)
  File "/home/zhou/anaconda3/envs/sc_depth_env/lib/python3.6/site-packages/detectron2-0.6-py3.6-linux-x86_64.egg/detectron2/utils/visualizer.py", line 402, in draw_instance_predictions
    masks = np.asarray(predictions.pred_masks)
  File "/home/zhou/anaconda3/envs/sc_depth_env/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

What is the cause of this problem？

**Comment by wondervictor** [comment]
Hi, @zhouzhou-github1, thanks for your interest in SparseInst.
This problem is due to the difference in versions. In dectron2 v0.3, it uses `BitMasks.tensor` to store the mask tensor. You can change the `/home/zhou/anaconda3/envs/sc_depth_env/lib/python3.6/site-packages/detectron2-0.6-py3.6-linux-x86_64.egg/detectron2/utils/visualizer.py` L402 by appending `tensor` to `pred_masks`, that is, `np.asarray(predictions.pred_masks.tensor)`.

**Comment by wondervictor** [comment]
You can refer to #10.

**Comment by zhouzhou-github1** [comment]
Thank you!

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
