### ISSUE TITLE
Error GenericMask cannot handle object {} of type '{}'

### ISSUE THREAD

**Issue by abdshomad** [hustvl/SparseInst#18]
## Error
Visualizing Images with SparseInst yields error. 
ERROR: ValueError("GenericMask cannot handle object {} of type '{}'".format(m, type(m)))
This same error occurred both on my Ubuntu laptop and also on Google Colab. 

## Expected Behavior
Visualizing Images with SparseInst should be successful 

## Error Log 
```
/content/SparseInst
[04/27 01:39:25 detectron2]: Arguments: Namespace(confidence_threshold=0.5, 
config_file='configs/sparse_inst_r50_giam.yaml', input=['datasets/coco/val2017/000000000139.jpg' ... ], 
opts=['MODEL.WEIGHTS', 'sparse_inst_r50_giam_aug_2b7d68.pth', 'INPUT.MIN_SIZE_TEST', '512'], 
output='results', video_input=None, webcam=False)
[04/27 01:39:28 fvcore.common.checkpoint]: [Checkpointer] 
Loading from sparse_inst_r50_giam_aug_2b7d68.pth ...
  0% 0/5000 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: 
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. 
(Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py:402: 
FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding 
protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). 
In the future, this object will be coerced as if it was first converted using `np.array(obj)`. 
To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array 
created with `np.empty(correct_shape, dtype=object)`.
  masks = np.asarray(predictions.pred_masks)
/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py:402: 
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences 
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. 
If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  masks = np.asarray(predictions.pred_masks)
  0% 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 96, in <module>
    img, args.confidence_threshold)
  File "/content/SparseInst/sparseinst/d2_predictor.py", line 69, in run_on_image
    predictions=instances)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py", line 403, 
in draw_instance_predictions
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py", line 403, in <listcomp>
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py", line 96, in __init__
    raise ValueError("GenericMask cannot handle object {} of type '{}'".format(m, type(m)))
ValueError: GenericMask cannot handle object tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]]) of type '<class 'torch.Tensor'>'
```

## Possible Solution
Change PyTorch to specific version? 

## Steps to Reproduce
Use Link below: 
https://colab.research.google.com/drive/1EdzVwbXKsIGDFyQtb92Ppo22oQ4rChnL#scrollTo=VtxB2v--pPZA
1. Git Clone SparseInst 
2. Install Dependencies (timm) 
3. Download model 
4. Download COCO Datasets (val2017 Only)
5. Run 
python demo.py --config-file configs/sparse_inst_r50_giam.yaml --input datasets/coco/val2017/* --output results --opt MODEL.WEIGHTS sparse_inst_r50_giam_aug_2b7d68.pth INPUT.MIN_SIZE_TEST 512

## Environment 1 
* Using Google Colab 
* CUDA Version: 11.2 
* Install Detectron2 using pip install
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

## Environment 2 
* Using Ubuntu 20.04 
* GPU: NVIDIA GeForce RTX 3060 Laptop GPU 
* CUDA Version: 11.4
* Install Detectron2 from source on newly created conda environment

**Comment by Roserland** [comment]
It's the bug of detectron2/

Try this way:
"/usr/local/lib/python3.7/dist-packages/detectron2/utils/visualizer.py", line 403,

modify the code from 
`masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]`
to
`masks = [GenericMask(x.numpy(), self.output.height, self.output.width) for x in masks]`

**Comment by abdshomad** [comment]
> 

Excellent. I confirmed the above solution works! 
Check it out here: https://colab.research.google.com/drive/1EdzVwbXKsIGDFyQtb92Ppo22oQ4rChnL#scrollTo=VtxB2v--pPZA
