### ISSUE TITLE
error when inference on mp4

### ISSUE THREAD

**Issue by Wooho-Moon** [hustvl/SparseInst#24]
i meet some error when i run demo.py by:

python demo.py --config-file configs/sparse_inst_r50_giam.yaml --video-input test.mp4 --output results --opt MODEL.WEIGHTS sparse_inst_r50_giam_aug_2b7d68.pth INPUT.MIN_SIZE_TEST 512

it returns:

Traceback (most recent call last):
  File "/home/usr/workspace/instance_segementation/SparseInst-main/demo.py", line 160, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video, args.confidence_threshold), total=num_frames):
  File "/home/usr/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/usr/workspace/instance_segementation/SparseInst-main/sparseinst/d2_predictor.py", line 136, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/usr/workspace/instance_segementation/SparseInst-main/sparseinst/d2_predictor.py", line 103, in process_predictions
    vis_frame = video_visualizer.draw_instance_predictions(
  File "/home/usr/workspace/instance_segementation/detectron2/detectron2/utils/video_visualizer.py", line 86, in draw_instance_predictions
    np.asarray(np.asarray(masks.tensor.permute(1, 2, 0)), dtype=np.uint8, order="F")
AttributeError: 'Tensor' object has no attribute 'tensor'

what should i do?

**Comment by wondervictor** [comment]
Hi @Wooho-Moon, thanks for your interest in SparseInst!
For your problem, you can simply fix it by uncommenting this line:
https://github.com/hustvl/SparseInst/blob/c3f122c3fe2fbc7a58a38045c8b7627c81680676/sparseinst/sparseinst.py#L155

**Comment by Wooho-Moon** [comment]
Thinks for your reply. I can slove the error with another method fixing code! but i also solve the error with your anwer too!

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
