### ISSUE TITLE
运行python train_net.py --config-file my_config.yaml --num-gpus 1出错，求助！！！

### ISSUE THREAD

**Issue by dhagsdjsb** [hustvl/SparseInst#55]
Command Line Args: Namespace(config_file='my_config.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)

Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

Traceback (most recent call last):
  File "train_net.py", line 258, in <module>
    launch(
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net.py", line 239, in main
    cfg = setup(args)
  File "train_net.py", line 214, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/kotori/anaconda3/envs/sparse/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.SPARSE_INST'

**Comment by wondervictor** [comment]
Hi @dhagsdjsb, thanks for your interest in SparseInst!
You need to run the `train_net.py` of SparseInst, which will add the configs of SparseInst.

**Comment by dhagsdjsb** [comment]
我运行了，但是报错，不行。

**Comment by wondervictor** [comment]
Hi @dhagsdjsb, it seems that you haven't added the configs of SparseInst before training. You need to call `add_sparse_inst_config` to update the configs of SparseInst, as:
https://github.com/hustvl/SparseInst/blob/bd57455aa49c4cb37d66c77ccd477c7a5ebee444/train_net.py#L152

**Comment by dhagsdjsb** [comment]
非常感谢您的耐心指导！已经解决了！




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Tianheng ***@***.***&gt;;
Send time:&nbsp;Sunday, Jul 17, 2022 4:46 PM
***@***.***&gt;; 
Cc:&nbsp;"信息202001  ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [hustvl/SparseInst] 运行python train_net.py --config-file my_config.yaml --num-gpus 1出错，求助！！！ (Issue #55)





 
Hi @dhagsdjsb, it seems that you haven't added the configs of SparseInst before training. You need to call add_sparse_inst_config to update the configs of SparseInst, as:
 https://github.com/hustvl/SparseInst/blob/bd57455aa49c4cb37d66c77ccd477c7a5ebee444/train_net.py#L152

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
