### ISSUE TITLE
为什么评估以及测速都有这个问题？AssertionError: A prediction has category_id=4, which is not available in the dataset.

### ISSUE THREAD

**Issue by dhagsdjsb** [hustvl/SparseInst#60]

**Comment by dhagsdjsb** [comment]
> Traceback (most recent call last): File "test_net.py", line 227, in test_sparseinst_speed(cfg) File "test_net.py", line 162, in test_sparseinst_speed results = evaluator.evaluate() File "/home/bdas/lijiao/SparseInst-onnx-export/detectron2/detectron2/evaluation/coco_evaluation.py", line 185, in evaluate self._eval_predictions(set(self._tasks), predictions, img_ids=img_ids) File "/home/bdas/lijiao/SparseInst-onnx-export/detectron2/detectron2/evaluation/coco_evaluation.py", line 204, in _eval_predictions assert ( AssertionError: A prediction has category_id=4, which is not available in the dataset.
