### ISSUE TITLE
Enabling FP16 AMP causes error

### ISSUE THREAD

**Issue by siddagra** [hustvl/SparseInst#70]
Enabling mixed precision using:

```
python3 train_net.py --config-file configs/sparse_inst_r50vd_dcn_giam_aug.yaml --num-gpus 1 SOLVER.AMP.ENABLED True
```

causes error:

```
Traceback (most recent call last):
  File "train_net.py", line 180, in <module>
    launch(
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 174, in main
    return trainer.train()
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/siddharth/7200rpm Seagate/rice-counting/SparseInst/sparseinst/sparseinst.py", line 99, in forward
    features = self.backbone(images.tensor)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/siddharth/7200rpm Seagate/rice-counting/SparseInst/sparseinst/backbones/resnet.py", line 371, in forward
    x = self.layer3(x)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/siddharth/7200rpm Seagate/rice-counting/SparseInst/sparseinst/backbones/resnet.py", line 93, in forward
    x = self.conv2(x, offset)
  File "/home/siddharth/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 383, in forward
    x = deform_conv(
  File "/home/siddharth/.local/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 61, in forward
    _C.deform_conv_forward(
RuntimeError: expected scalar type Half but found Float
```

pytorch 1.10.0+cu116

**Comment by wondervictor** [comment]
Hi @siddagra, thanks for your interest in SparseInst!
It seems that FP16 cannot support deformable conv in detectron2, I'll check it soon.

**Comment by kirillkoncha** [comment]
> Hi @siddagra, thanks for your interest in SparseInst!
> It seems that FP16 cannot support deformable conv in detectron2, I'll check it soon.

Hello again! Did you find anything? With this error it is impossible now to train R-50-vd-DCN model? Or there is way to turn off FP16 or mixed precision?

**Comment by wondervictor** [comment]
Hi @kirillkoncha and @siddagra, I haven't found an elegant solution to enable FP16 for deformable convolution implemented in detectron2 due to the limited time recently. However, I have some practical methods:
1) change the input to `deformable_conv_cuda` to `float` and then cast the output of the deformable convolution to `half` for FP16, 
2) check whether the official detectron2 has provided the FP16-supported version of deformable convolution.

**Comment by 116022017144** [comment]
> 

hello，i don't know how to modify it specifically,can you tell me?Thank you!
