### ISSUE TITLE
CSPDarknet53 as a backbone

### ISSUE THREAD

**Issue by koolvn** [hustvl/SparseInst#82]
Hi! How can I use CSPDarknet53 as a backbone? Are there pretrained weights? Thanks in advance :)

**Comment by wondervictor** [comment]
Hi @koolvn, the pre-trained weights of CSPDarknet53 can be downloaded from [timm](https://github.com/rwightman/pytorch-image-models/blob/a520da9b495422bc773fb5dfe10819acb8bd7c5c/timm/models/cspnet.py#L52), or you can use the YOLO pre-trained version for higher performance.

**Comment by koolvn** [comment]
Thank you! And what about usage of [CSPDarknet53 config](https://github.com/hustvl/SparseInst/blob/main/configs/sparse_inst_cspdarknet53_giam.yaml)?
I've tried passing its config to train_net.py but failed with the following error:
```Traceback (most recent call last):
  File "tools/train_net.py", line 209, in <module>
    launch(
  File "/workspace/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_net.py", line 201, in main
    trainer = Trainer(cfg)
  File "/workspace/detectron2/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/workspace/detectron2/detectron2/engine/defaults.py", line 505, in build_model
    model = build_model(cfg)
  File "/workspace/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/workspace/SparseInst/./sparseinst/sparseinst.py", line 35, in __init__
    self.backbone = build_backbone(cfg)
  File "/workspace/detectron2/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/workspace/SparseInst/./sparseinst/backbones/cspnet.py", line 417, in build_cspnet_backbone
    model = CSPNet(
  File "/workspace/SparseInst/./sparseinst/backbones/cspnet.py", line 333, in __init__
    str(i), stage_fn(prev_chs, **sa, **layer_args, block_fn=block_fn))
  File "/workspace/SparseInst/./sparseinst/backbones/cspnet.py", line 247, in __init__
    self.conv_down = ConvBnAct(
TypeError: __init__() got an unexpected keyword argument 'aa_layer'
```

**Comment by koolvn** [comment]
@wondervictor  Should I change something in Base-SparseInst.yaml?

**Comment by koolvn** [comment]
@wondervictor I was able to get it working by commenting out several lines in `backbones/cspnet.py` which referred to "unexpected kwarg" TypeError

**Comment by wondervictor** [comment]
@koolvn  I see... Maybe the implementation from `timm` has been updated for several rounds.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 .
