### ISSUE TITLE
RuntimeError: Given input size: (256x9x27). Calculated output size: (256x0x2). Output size is too small

### ISSUE THREAD

**Issue by YaoJiawei329** [hustvl/SparseInst#92]
Hi, I am using detectron2 v0.6, train on coco2017, but it occur a RuntimeError: Given input size: (256x9x27). Calculated output size: (256x0x2). Output size is too small. 
[10/25 22:08:38 d2.utils.events]:  eta: 3 days, 11:34:06  iter: 7329  total_loss: 3.163  loss_ce: 1.256  loss_objectness: 0.5939  loss_dice: 1.001  loss_mask: 0.3219  time: 1.1804  data_time: 0.0963  lr: 5e-05  max_mem: 8099M
Traceback (most recent call last):
  File "train_net.py", line 196, in <module>
    launch(
  File "c:\users\f\detectron2\detectron2\engine\launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 190, in main
    return trainer.train()
  File "c:\users\f\detectron2\detectron2\engine\defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "c:\users\f\detectron2\detectron2\engine\train_loop.py", line 150, in train
    self.after_step()
  File "c:\users\f\detectron2\detectron2\engine\train_loop.py", line 180, in after_step
    h.after_step()
  File "c:\users\f\detectron2\detectron2\engine\hooks.py", line 555, in after_step
    self._do_eval()
  File "c:\users\f\detectron2\detectron2\engine\hooks.py", line 528, in _do_eval
    results = self._func()
  File "c:\users\f\detectron2\detectron2\engine\defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "c:\users\f\detectron2\detectron2\engine\defaults.py", line 617, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "c:\users\f\detectron2\detectron2\evaluation\evaluator.py", line 158, in inference_on_dataset
    outputs = model(inputs)
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\YaoJiawei\python_workspace\SparseInst_TensorRT\sparseinst\sparseinst.py", line 101, in forward
    features = self.encoder(features)
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\YaoJiawei\python_workspace\SparseInst_TensorRT\sparseinst\encoder.py", line 82, in forward
    prev_features = self.ppm(self.fpn_laterals[0](features[0]))
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\YaoJiawei\python_workspace\SparseInst_TensorRT\sparseinst\encoder.py", line 38, in forward
    priors = [F.interpolate(input=F.relu_(stage(feats)), size=(
  File "D:\YaoJiawei\python_workspace\SparseInst_TensorRT\sparseinst\encoder.py", line 38, in <listcomp>
    priors = [F.interpolate(input=F.relu_(stage(feats)), size=(
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ana\envs\detectron2\lib\site-packages\torch\nn\modules\pooling.py", line 622, in forward
    return F.avg_pool2d(input, self.kernel_size, self.stride,
RuntimeError: Given input size: (256x9x27). Calculated output size: (256x0x2). Output size is too small

**Comment by wondervictor** [comment]
Hi, thanks for your interest in SparseInst 😄.
The input size is too small, which causes this error. Could you tell me what input size is used in your setting?

**Comment by YaoJiawei329** [comment]
> Hi, thanks for your interest in SparseInst 😄. The input size is too small, which causes this error. Could you tell me what input size is used in your setting?

Do you mean this in Base-SparseInst.yaml, I did not change this. Should I delete 416, even 448? 
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 853
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 853
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"

**Comment by wondervictor** [comment]
This problem is weird and have you re-run the training?

**Comment by YaoJiawei329** [comment]
> This problem is weird and have you re-run the training?

It occured twice on COCO2017 yesterday, while never happen on selfdata(about 800*1500), maybe some picture too small in COCO.

**Comment by wondervictor** [comment]
I've never met the error when training COCO and I'd like to check this problem. Maybe I need to know what you've modified already.

**Comment by YaoJiawei329** [comment]
The first thing I did aftering download this repo was try to train on COCO2017. So, at the beginning, I did not change anything, just unzip COCO2017 annotations, train2017 and val2017, put them into datasets. Run this command:
python train_net.py --config-file configs/sparse_inst_r50vd_dcn_giam_aug.yaml --num-gpus 1

"RuntimeError: Given input size: (256x9x27). Calculated output size: (256x0x2). Output size is too small" occured after 3 minutes for the first time, and occured after about 2 hours for the second time. I google the RuntimeError, and I guess some pictures may been resized into a small size, but I did not catch. Maybe I should try again when the GPU(RTX3060) is free.

**Comment by wondervictor** [comment]
Ok, I see. I'll check it soon whether the augmentation in v0.6 causes this error.
